app.swagger.ui:
  path: /
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger.json:
  path: /swagger.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }